### ISSUE TITLE
Could I uninstall com.miui.guardprovider directly?

### ISSUE THREAD

**Issue by widsnoy** [MinaMichita/AntiAntiDefraud#1]
Sorry, this question has nothing to do with modules. I am just wondering if this could be a way to protect privacy.

**Comment by TonyShizuku** [comment]
删除com.miui.guardprovider是安全的，参见 https://t.me/MeAndMyPY/9901 .

如果您具有Root权限可以直接扬了它。


```
adb shell su -c "pm uninstall com.miui.guardprovider"
```

请相互转告。

---

It's safe to delete it,see https://t.me/MeAndMyPY/9901 .

And If you have ROOT Permission,you could directly do it.

```
adb shell su -c "pm uninstall com.miui.guardprovider"
```

PLZ Forward it.

**Comment by widsnoy** [comment]
> 删除com.miui.guardprovider是安全的，参见 https://t.me/MeAndMyPY/9901 .
> 
> 如果您具有Root权限可以直接扬了它。
> 
> ```
> adb shell su -c "pm uninstall com.miui.guardprovider"
> ```
> 
> 请相互转告。
> 
> It's safe to delete it,see https://t.me/MeAndMyPY/9901 .
> 
> And If you have ROOT Permission,you could directly do it.
> 
> ```
> adb shell su -c "pm uninstall com.miui.guardprovider"
> ```
> 
> PLZ Forward it.

Thank you.
